name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or 'master' if that's your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload static site
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."  # Adjust if your site is inside a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
